sudo: required
language: node_js
node_js:
  - node

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_script:
- npm install -g @angular/cli

script: 
- ng test -- --watch=false
