sudo: required
dist: trusty
language: node_js
node_js:
  - node

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli

script: 
- ng test -- --watch=false

notification:
  email: false
