sudo: false
language: node_js
node_js:
  - node

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_script:
- npm install

script: 
- npm run test -- --watch=false

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run build;
    fi
