sudo: false
language: node_js
node_js:
  - node

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install

script: 
- ng test -- --watch=false
