sudo: true
dist: trusty
language: node_js
node_js:
  - node

branch:
  only:
  - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli

script: 
  - ng test --watch=false -cc
  - npm run e2e
  - ng build
